apiVersion: v1
data:
  local.js: |+
    window.config = {
        "REACT_APP_DEV_CENTRAL_APP_URL": "http://localhost:3000",
        "REACT_APP_SPEC_VALIDATOR_URL": "http://3.218.141.44:9001",
        "REACT_APP_SPEC_MNGR_URL": "http://3.218.141.44:9001",
        "REACT_APP_PROXY_GEN_URL": "http://3.218.141.44:9001",
        "REACT_APP_CONFIG_MNGR_URL": "http://3.218.141.44:9001",
        "REACT_APP_EDGE_SECURED_API_URL": "https://amer-mint-partner01-test.apigee.net",
        "REACT_APP_JENKINS_LOCATION_API": "http://107.23.248.181:8080",
        "REACT_APP_AZURE_AD_URL": "https://login.microsoftonline.com",
        "REACT_APP_AZURE_AD_TENANT_ID": "f2dd062d-3e19-44b1-aeef-11297fbec7e2",
        "REACT_APP_AZURE_AD_APP_CLIENT_ID": "caa10914-2e2a-4dbf-9ddc-bdd5af07dab8",
        "ENABLE_DEMO_LOGIN": true,
        "local": true
    }

kind: ConfigMap
metadata:
  name: local-configmap
  namespace: fedco
