apiVersion: v1
kind: Service
metadata:
  name: fedco-devcentral-app-local
spec:
  selector:
    app: fedco-devcentral-app-local
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: 3000
      protocol: TCP
