---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fedco
  name: fedco-devcentral-app-local  
  labels:
    app: fedco-devcentral-app-local
  annotations:
    fluxcd.io/automated: "true"    
    fluxcd.io/tag.fedco-devcentral: semver:~1.1
spec:
  strategy:
    rollingUpdate:
      maxUnavailable: 0
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: fedco-devcentral-app-local
  template:
    metadata:
      name: fedco-devcentral-app-pod
      labels:
        app: fedco-devcentral-app-local
    spec:
      containers:
      - name: fedco-devcentral
        image: sagark24/fedco-app:1.1.1
        ports:
          - containerPort: 3000
        imagePullPolicy: Always
        volumeMounts:
          - name: config-js-volume
            mountPath: /app/build/config.js
            subPath: local.js        

      volumes:
        - name: config-js-volume
          configMap:
            name: local-configmap

