apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: fedco-devcentral-app-local
  namespace: fedco
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: fedco-devcentral-app-local
  minReplicas: 2
  maxReplicas: 4
  metrics:
  - type: Resource
    resource:
      name: cpu
      # scale up if usage is above
      # 99% of the requested CPU (10m)
      targetAverageUtilization: 99
